"""Repository, domain-service, and unit-of-work ports."""

from typing import Any, Protocol

from app.schemas.site_settings import SiteSettingsUpdateRequest


class NavigationRepository(Protocol):
    async def list_categories(self, include_auth_required: bool = True) -> list[Any]: ...
    async def list_category_names(self) -> list[str]: ...
    async def get_category_by_name(self, name: str) -> Any | None: ...
    async def get_max_category_order(self) -> int: ...
    async def create_category(self, name: str, auth_required: bool, sort_order: int) -> Any: ...
    async def update_category(self, category: Any, new_name: str, auth_required: bool) -> Any: ...
    async def delete_category(self, category: Any) -> None: ...
    async def reorder_categories(self, order_map: dict[str, int]) -> None: ...
    async def get_link_by_id(self, link_id: str) -> Any | None: ...
    async def get_link_rows_by_ids(self, link_ids: list[str]) -> list[Any]: ...
    async def list_link_ids_in_category(self, category_id: int) -> list[str]: ...
    async def list_links_by_category(self, category_id: int) -> list[Any]: ...
    async def get_max_link_order(self, category_id: int) -> int: ...
    async def create_link(
        self,
        category_id: int,
        title: str,
        url: str,
        icon: str | None,
        sort_order: int,
        link_id: str | None = None,
    ) -> Any: ...
    async def update_link(
        self,
        link: Any,
        title: str,
        url: str,
        icon: str | None,
        *,
        category_id: int | None = None,
        sort_order: int | None = None,
    ) -> Any: ...
    async def delete_link(self, link: Any) -> None: ...
    async def reorder_links(self, order_map: dict[str, int]) -> None: ...
    async def flush(self) -> None: ...


class NavigationService(Protocol):
    async def get_all_categories(self, include_auth_required: bool = True) -> dict: ...
    async def get_category_by_name(self, name: str) -> Any | None: ...
    async def create_category(self, name: str, auth_required: bool = False) -> Any: ...
    async def update_category(self, old_name: str, new_name: str, auth_required: bool) -> Any | None: ...
    async def delete_category(self, name: str) -> bool: ...
    async def add_link(
        self,
        category_name: str,
        title: str,
        url: str,
        icon: str | None = None,
        link_id: str | None = None,
    ) -> dict: ...
    async def get_link_by_id(self, link_id: str) -> Any | None: ...
    async def update_link(
        self,
        link_id: str,
        title: str,
        url: str,
        icon: str | None,
        new_category_name: str | None = None,
    ) -> dict | None: ...
    async def delete_link(self, link_id: str) -> bool: ...
    async def reorder_link(self, link_id: str, direction: str) -> bool: ...
    async def batch_reorder_links(self, link_ids: list[str]) -> bool: ...
    async def batch_reorder_categories(self, category_names: list[str]) -> bool: ...


class ArticleRepository(Protocol):
    async def list_articles_async(
        self,
        protected_paths: list[str],
        include_protected: bool,
    ) -> list[dict]: ...
    async def get_article_async(
        self,
        path: str,
        protected_paths: list[str],
        allow_protected: bool,
    ) -> dict: ...
    async def sync_article_async(
        self,
        path: str,
        content: str,
        title: str | None = None,
        frontmatter: dict | None = None,
    ) -> dict: ...
    async def update_article_async(self, path: str, content: str) -> dict: ...
    async def delete_article_async(self, path: str) -> dict: ...


class FolderRepository(Protocol):
    async def list_folders_async(self) -> list[dict]: ...
    async def create_folder_async(self, name: str) -> dict: ...
    async def rename_folder_async(self, name: str, new_name: str) -> dict: ...
    async def delete_folder_async(self, name: str) -> dict: ...


class SettingsRepository(Protocol):
    async def get_settings(self, use_cache: bool = True) -> dict: ...
    async def get_public_settings(self, use_cache: bool = True) -> dict: ...
    async def update_settings(self, payload: SiteSettingsUpdateRequest) -> dict: ...


class LogRepository(Protocol):
    async def record_visit(self, ip: str, path: str, user_agent: str = "") -> None: ...
    async def record_update(
        self,
        action: str,
        target_type: str,
        target_name: str,
        details: str = "",
        username: str = "",
    ) -> None: ...
    async def get_visits(self, limit: int = 100) -> dict: ...
    async def clear_visits(self) -> None: ...
    async def get_updates(self, limit: int = 100) -> dict: ...
    async def clear_updates(self) -> None: ...


class UnitOfWork(Protocol):
    navigation: NavigationService
    articles: ArticleRepository
    folders: FolderRepository
    settings: SettingsRepository
    logs: LogRepository

    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
